# +----------------------------------------------------------------------------------------------+
# |                                                                                              |
# |                                       Darkness Liquidation                                   |
# |                                                                                              |
# |                               Discord: https://dsc.gg/darkness-liquidation                   |
# |                                                                                              |
# |                                 Authors: 1hendex x clopdisabler                              |
# |                                                                                              |
# +----------------------------------------------------------------------------------------------+

# Для запуска Darkness требуется лицензия (предоставляется при покупке)
your_license: "null"

alerts:
  # Кроме трансляции оповещений игрокам, должны ли они также отправляться на консоль?
  print_to_console: true
  # Это контролирует, будут ли/как будут передаваться оповещения между серверами, подключенными к вашему прокси.
  # У вас должен быть включен 'bungee-plugin-message-channel' в конфигурации Velocity, если используется Velocity.
  proxy:
    # Следует ли отправлять оповещения на другие серверы, подключенные к вашему прокси-серверу?
    send: false
    # Должны ли оповещения, полученные с других серверов, быть объявлены на этом сервере?
    receive: false

verbose:
  print_to_console: false

# Включить ли тестовый режим?
# Если этот режим включён, команды наказания, вращения и перемешивания слотов не будут работать.
test_mode: false

# Тема, которую будет использовать Darkness
theme: default

# Client Settings
client_settings:

  # Client Alert Settings
  alert:

    # Должны ли мы отправлять предупреждение, когда игрок присоединяется, указывая его бренд клиента?
    enabled: true

    # Удаляет следующий регулярное выражение из названия клиента
    remove: " \\(Velocity\\)$"

    # Это означает, что она не будет транслировать свой бренд операторам, если бренд соответствует следующим регексам
    ignored_clients:
      - "^badlion$"
      - "^optifine$"
      - "^vanilla$"
      - "^fabric$"
      - "^Feather Fabric$"
      - "(^lunarclient:v\\d+\\.\\d+\\.\\d+-\\d{4}$)|(^lunarclient:[a-z0-9]{7}/[\\w_/-]{3,32}$)"
      - "^labymod$"

  # Клиентские бренды, содержащие следующие название, будут заблокированы от входа на сервер
  banned_clients:
    - "^1.12.2$"
    - "^mcp$"
    - "^ForgeOptiFine 1.16.5/forge/modified$"
    - ".*/.*"

  # Минимальная/Максимальная длина имени бренда клиента.
  symbol_limiter: 5:16
  # Нужно ли проверять количество капса (рекомендуется не отключать, чтобы распознавать подмены типа FORGE, VANILLA) (-1 чтобы отключить)
  caps_percentage: 70
  # Блокировка использования недопустимых символов в имени бренда.
  whitelist_regex: "^[a-zA-Z0-9:_/, .-]+$"
  # Нужно ли блокировать чит клиенты по подозрительным признакам (например Delta Client и другие)
  cheat_detector: true
  # Даркнесс будет блокировать клиентов по имени бренда с помощью регекса.
  # Если имя клиента совпадает с этим регексом, он не сможет зайти на сервер.
  payload:
    - "Remix"
    - "forgewurst"
    - "CRYSTAL"
    - "matrix"
    - "CrystalWare"
    - "Misplace"
    - "reach"
    - "lmaohax"
    - "Reach Mod"
    - "cock"
    - "Vape v3"
    - "1946203560"
    - "#unbanearwax"
    - "EARWAXWASHERE"
    - "Cracked Vape"
    - "EROUAXWASHERE"
    - "moon:exempt"
    - "Vape"
    - "WDL|INIT"
    - "WDL|CONTROL"
    - "Bspkrs Client"

  # Даркнесс будет вносить в чёрный список определённые версии Forge, которые содержат встроенные читы на дальность удара (Reach) (Forge 1.18.2 — 1.19.3).
  # Установка этого параметра в false позволит таким клиентам подключаться к серверу.
  # Отключайте это на свой страх и риск.
  disconnect_blacklisted_forge_versions: true

# Packet Settings
packet_settings:

  # Максимальное количество пропущенных транзакций, после которого игрок кикается
  # Срабатывает, при FreeCam, BackTrack, Blink
  transaction_skip: 400
  # Сколько времени должно быть у игроков, пока мы не выкинем их за тайм-аут? По умолчанию = 45 секунд
  transaction_time: 45
  # Максимально допустимое отрицательное смещение таймера игрока, после которого кикаем (в миллисекундах)
  # Срабатывает при Timer (0.1), Freeze
  negative_timer: 5000
  # Эта настройка применяется только к клиентам 1.17–1.20.5 на серверах 1.8
  cancel_duplicate_packet: true
  # Игнорировать ли ротацию в дублирующихся пакетах?
  ignore_duplicate_packet_rotation: true
  # Включите это, чтобы запретить Даркнесс отменять пакеты pong, полученные от игроков.
  # Это может улучшить совместимость с другими античитами. Может вызвать проблемы с ограничителями пакетов.
  # Не включайте это, если не уверены, что делаете.
  disable_pong_cancelling: false
  # Даркнесс иногда отменяет незаконные пакеты, например, с таймером, после X пакетов в секунду отмененных, когда следует
  # нам просто кикнуть игрока? Это необходимо, так как некоторые ограничители пакетов не учитывают пакеты, отмененные Даркнесс.
  packet_spam_threshold: 100
  # Даркнесс может обеспечить, что игрок, выведенный из состояния полёта, не может иметь пинг более X миллисекунд.
  # Это связано с тем, что Даркнесс в настоящее время не проверяет летающих игроков.
  max_ping_out_of_flying: 300
  # Максимальный пинг, когда усиление фейерверка снимается с игрока.
  # Это не позволяет игрокам с высокой задержкой использовать 1 усиление фейерверка с надкрыльями навсегда.
  max_ping_firework_boost: 1000

# Настройки команд наказания // Не рекомендуется к использованию - скоро будет удалено
point_command:

  # Команды, которые будут выполняться при различных условиях (например, при нарушениях)
  '1': darkness rotate %PLAYER%
  '2': darkness shuffle %PLAYER% many
  '3': darkness rotate %PLAYER%
  '4': darkness shuffle %PLAYER% many
  '6': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '7': darkness crash %PLAYER% particle
  '8': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '9': darkness ban %PLAYER% %prefix% &cПодозрение в использовании читов
  '21': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '26': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '30': darkness ban %PLAYER% %prefix% &cПодозрение в использовании читов
  '34': darkness kick %PLAYER% %prefix% &cПодозрение в использовании читов
  '38': darkness ban %PLAYER% %prefix% &cПодозрение в использовании читов

# Punish Command Settings
punish_command:

  # Какую анимацию наказания должна показывать Даркнесс перед киком игрока?
  # Анимации: NONE, THOR, FIRE, ERROR, SHAME или RANDOM для выбора случайной анимации каждый раз
  animation: NONE

  # Должны ли мы отправлять сообщение в чат, когда игрок наказывается Даркнесс?
  broadcast: true

  # Какую команду должна выполнить Даркнесс после завершения анимации наказания? (%nl% для новой строки)
  # Плейсхолдеры: %prefix% -> (Префикс Даркнесс), %player% -> (Игрок, который был наказан), %reason% -> (Причина, указанная в команде наказания Даркнесс)
  command: darkness kick %player% %prefix% %reason%

# Punish Wave Settings
punishwave:

  # Включить ли Волну Наказаний?
  # Если Волна Наказаний включена, Даркнесс накажет всех читеров одновременно
  # Если игрок был наказан с помощью команды /darkness punish при включённой Волне Наказаний,
  # он будет добавлен в очередь и наказан, когда начнётся Волна Наказаний
  enabled: false

  # Должна ли Даркнесс оповещать об этом событии?
  broadcast: true

  # Как часто должна выполняться Волна Наказаний? (в минутах)
  time: 15

  # Обратный отсчёт перед выполнением Волны Наказаний (-1 чтобы отключить)
  countdown: 5

# Ban Command Settings
ban_command:

  # Должны ли мы отправлять сообщение в чат, когда игрок наказывается Даркнесс?
  broadcast: true

  # Плейсхолдеры: %player% -> (Игрок, который был наказан), %reason% -> (Причина, указанная в команде наказания Даркнесс)
  command: ban %player% %reason%

# Discord Sync Settings
discord:

  # Вы хотите синхронизировать Даркнесс с вашим Discord-сервером?
  enabled: false

  # Вставьте URL вебхука канала
  webhook_url: ""
  # Заголовок сообщения
  embed_title: "**:fire: ОБНАРУЖЕН НОВЫЙ ЧИТЕР!**"
  # Цвет полосы слева от сообщения
  embed_color: "#ff0000"

  # Содержимое сообщения
  violation_content:
    - "%player%"
    - ""
    - ":shield: **Режим:**"
    - "%server_name%"
    - ""
    - ":package: **Тип чита:**"
    - "%check%"
    - ""
    - ":bar_chart: **Уровень:**"
    - "%violations%"
    - ""
    - ":desktop: **Клиент:**"
    - "%brand%"
    - ""
    - ":pushpin: **Версия:**"
    - "%version%"
    - ""
    - ":signal_strength: **PING | TPS:**"
    - "%ping% | %tps%"

  # Хотите, чтобы Даркнесс отправляла сообщения в Discord,
  # когда игроки наказываются во время Punish Wave?
  punishwave: false
  punishwave_title: "**:fire: ОБНАРУЖЕНА ВОЛНА НОВЫХ ЧИТЕРОВ!**"

  # Содержимое сообщения
  punishwave_content:
    - ":shield: **Режим**"
    - "%server_name%"
    - ""
    - ":busts_in_silhouette: **Игроки, которых наказали**"
    - "%players_punishwave%"
    - ""

  # Заголовок дополнительного поля в эмбеде
  embed_field: "Информация:"

# Log Settings
logs:

  # Какой тип логирования использовать Даркнесс?
  # Типы: YAML_ONE, YAML_DAYS, MYSQL, SQLITE, NONE
  # 1. YAML_ONE - Логирует все флаги в один файл data.yml
  # 2. YAML_DAYS - Логирует каждый день в отдельный файл внутри папки logs
  # 3. SQLITE - Логирует в базу данных SQLite
  # 4. MYSQL - Логирует в базу данных MySQL
  # 5. NONE - Отключает логирование
  type: YAML_ONE

  # Логи, старше этого значения в днях, будут удалены
  clear_days: 7

  # Настройки MySQL (требуется тип MYSQL)
  mysql:
    host: localhost
    port: 3306
    database: database
    user: root
    password: ''
    use_ssl: false

    # Настройки пула соединений MySQL
    # Не изменяйте, если не знаете, что делаете
    pool_settings:
      maximum_pool_size: 50
      minimum_idle: 30
      maximum_lifetime: 1800000
      connection_timeout: 30000
      leak_detection_threshold: 0

## InformationHider Check
InformationHider:

  # Включить модуль скрытия информации?
  enabled: true

  # Проверять только игроков или всех сущностей?
  onlyForPlayers: true

  # Скрывает данные об игроках и мобах, чтобы чит-клиенты не могли получить лишнюю инфу.
  # На обычной игре это не заметно, но мешает читам.
  parts:
    # Спуфит здоровье — мобы и игроки всегда показывают фейковое здоровье
    # Полезно против хп-баров в модах и читах
    health:
      # Укажите значение, которое должна спуфить Darkness игрокам от 0 до 20.
      # При значении 0 множество KillAura будут сломаны, но ломает анимации ходьбы,
      # не советуется, если не хотите, чтобы игроки ходили "лунной походкой".
      value: 20
      # Если включено будет использоваться случайное значение от 0 до 20.
      # Менее заметно для игроков и лучше сохраняет процесс игры.
      random: false

    # Маскирует внутренние данные игрока, чтобы модули читов не могли их использовать.
    # Скрывает реальный уровень опыта, чтобы предотвратить отображение у читов.
    xp: true
    # Скрывает уровень кислорода, чтобы предотвратить отображение точного количества воздуха.
    air: true
    # Скрывает уровень сытости. Ломает работу функций AutoEat в чит-клиентах.
    saturation: true
    # Скрывает реальный пинг в табе. Предотвращает некоторые обходы в модулях AntiBot.
    ping: true
    # Скрывает режим игры. Читы всегда будут видеть игрока в Creative.
    gamemode: true
    # Отправляет фейковый сид мира, чтобы читы не могли найти руды и структуры по сиду.
    seed: true
    # Скрывает данные о здоровье и статистике из скорбордов и таба.
    scoreboard: true

    # Маскирует экипировку и визуальные эффекты игроков.
    # Скрывает зачарования на броне и предметах, чтобы читы не видели их тип и уровень.
    enchant: true
    # Скрывает точное количество предметов в руках и инвентаре.
    item_count: true
    # Заменяет настоящие названия предметов в руках на случайные.
    item_name: true
    # Скрывает названия и количество предметов, которые валяются на земле.
    item_drop: true
    # Всегда показывает полную прочность вещей, чтобы читы не видели износ брони.
    durability: true
    # Скрывает эффекты зелий от чужих глаз (чтобы не видели силу, скорость и т.д.).
    potion: true
    # Спамит читу ложными пакетами эффектов, полностью забивая его PotionList мусором.
    end_effect: true
    # Перемешивает предметы в инвентаре во время движения, ломая работу AutoTotem, InvWalk.
    inventory: true

    # Модуль создаёт фейковых модераторов в табе, чтобы скрыть настоящих модеров от читов.
    # Не переживайте эти боты существуют только на чит-клиенте, реальные игроки их не видят.
    fake_staff:
      # Нужно ли создавать фейковых ботов для маскировки реальной администрации?
      enabled: true
      # Если true, Darkness всегда будет создавать ботов со случайными именами.
      # Это улучшает совместимость с некоторыми серверами, но иногда позволяет обойти StaffList.
      only_random_name: false
      # Укажите настоящие префиксы вашей модерации, которые будут отображаться у фейковых ботов.
      roles:
        - "&cAdmin"
        - "&cStaff"
        - "&cHelper"
        - "&cModer"
      # Рекомендуется ставить значение >= 60, чтобы читы не могли отфильтровать настоящих модераторов.
      bots: 60

    # Настройки зрителей (с permission: darkness.spectator)
    spectators:
      # Будет делать зрителей скрытыми только в этих мирах. Оставьте пустым, чтобы разрешить все миры
      allowed_worlds:
        - ""
      # Скрыть всех зрителей с разрешением darkness.spectator, независимо от того, являются ли они активными зрителями.
      hide_spectators: true

# Compatibility Settings
compatibility:

  # Включите, если у вас кроссплатформенный проект. Это исключит игроков Bedrock
  # из проверок, чтобы избежать ложных срабатываний.
  geyser: true

  # Включите, если вы разрешаете мод ItemsScroller. Это позволит избежать
  # ложных срабатываний при быстром перемещении предметов.
  itemsScroller: false

  # Включите, если вы разрешаете мод TapeMouse. Это предотвратит флаги
  # на афк фармилках, где удары идут в один и тот же тайминг.
  tapeMouse: false

  # Включите, если вы разрешаете макросы на клавиши. Это поможет избежать
  # ложных срабатываний при вводе команд при ходьбе.
  keybind: false

  # Нужно ли учитывать кинематографическую камеру?
  # Настоятельно рекомендуется не включать эту опцию, так как это сделает проверки аим менее эффективными
  # В реальном боевом сценарии ни один из противников не будет сражаться, используя кинематографическую камеру
  account_cinematic: false

# Включить запись в журнал плагинов, которые внедрились в netty при присоединении для отладки проблем совместимости
debug_pipeline_on_join: false

# Включает экспериментальные проверки
experimental_checks: false

# Логгер для просмотра пакетов которые кидают игроки, полезно для разработчиков
packet_logger:
  enabled: false

  # Укажите ниже игроков, у которых будут логироваться все пакеты в консоль
  whitelist:
    - 1hendex

  # Список пакетов, которые нужно игнорировать
  # Чтобы узнать правильные имена, откройте гитхаб PacketEvents и найдите имена
  # Путь: https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/protocol/packettype/PacketType.java
  ignore:
    - WINDOW_CONFIRMATION
    - KEEP_ALIVE
    - PONG

# Название сервера, которое будет отображаться в логах игроков и сообщениях Discord
server_name: Darkness Server

# Укажите название или названия для команд Даркнесс.
# Первое название в списке станет основной командой плагина.
# Изменения применяются только после перезагрузки сервера.
command_name: darkness,dl

# Стоит ли нам отключить разрешение на обход?
# Если включено, Даркнесс проверит всех игроков, включая операторов
# Отключите это для некоторого прироста производительности
disable_bypass_permission: false

config:
  checks_updates: true
  lang: ru
  version: 1
