# +----------------------------------------------------------------------------------------------+
# |                                                                                              |
# |                                       Darkness Liquidation                                   |
# |                                                                                              |
# |                               Discord: https://dsc.gg/darkness-liquidation                   |
# |                                                                                              |
# |                                 Authors: 1hendex x clopdisabler                              |
# |                                                                                              |
# +----------------------------------------------------------------------------------------------+

# Для запуску Darkness потрібна ліцензія (надається після покупки)
your_license: "null"

alerts:
  # Окрім трансляції сповіщень гравцям, чи повинні вони також надсилатися на консоль?
  print_to_console: true
  # Це контролює, чи будуть/як будуть передаватися сповіщення між серверами, підключеними до вашого проксі.
  # У вас має бути включений 'bungee-plugin-message-channel' у конфігурації Velocity, якщо ви її використовуєте.
  proxy:
    # Чи слід надсилати сповіщення на інші сервери, підключені до вашого проксі-сервера?
    send: false
    # Чи повинні сповіщення, отримані з інших серверів, оголошуватися на цьому сервері?
    receive: false

verbose:
  print_to_console: false

# Чи потрібно увімкнути тестовий-режим?
# Якщо цей режим увімкнено, команди покарання, обертання та перемішування слотів не працюватимуть.
test_mode: false

# Тема, яку використовуватиме Darkness
theme: default

# Client Settings
client_settings:

  # Client Alert Settings
  alert:

    # Чи повинні ми надсилати попередження, коли гравець приєднується, вказуючи його бренд клієнта?
    enabled: true

    # Видаляє наступний регулярний вираз з назви клієнта
    remove: " \\(Velocity\\)$"

    # Це означає, що вона не транслюватиме його бренд операторам, якщо бренд відповідає наступним регулярним виразам
    ignored_clients:
      - "^badlion$"
      - "^optifine$"
      - "^vanilla$"
      - "^quilt$"
      - "^fabric$"
      - "^Feather Fabric$"
      - "(^lunarclient:v\\d+\\.\\d+\\.\\d+-\\d{4}$)|(^lunarclient:[a-z0-9]{7}/[\\w_/-]{3,32}$)"
      - "^labymod$"

  # Клієнтські бренди, що містять такі назви, будуть заблоковані від входу на сервер
  banned_clients:
    - "^1.12.2$"
    - "^mcp$"
    - "^ForgeOptiFine 1.16.5/forge/modified$"
    - ".*/.*"

  # Мінімальна/Максимальна довжина назви бренду клієнта.
  symbol_limiter: 5:16
  # Блокування використання неприпустимих символів у назві бренду.
  whitelist_regex: "^[a-zA-Z0-9:_/, .-]+$"
  # Чи перевіряти кількість капсу (рекомендовано не вимикати, щоб виявляти підміни типу FORGE, VANILLA) (-1 щоб вимкнути)
  caps_percentage: 70
  # Чи потрібно блокувати чит клієнти за підозрілими ознаками (наприклад Delta Client та інші)
  cheat_detector: true
  # Darkness блокуватиме клієнтів за назвою бренду за допомогою регексу.
  # Якщо назва клієнта співпадає з цим регексом, він не зможе зайти на сервер.
  payload:
    - "Remix"
    - "CRYSTAL"
    - "matrix"
    - "CrystalWare"
    - "Misplace"
    - "reach"
    - "lmaohax"
    - "Reach Mod"
    - "cock"
    - "Vape v3"
    - "1946203560"
    - "#unbanearwax"
    - "EARWAXWASHERE"
    - "Cracked Vape"
    - "EROUAXWASHERE"
    - "moon:exempt"
    - "Vape"
    - "WDL|INIT"
    - "WDL|CONTROL"
    - "Bspkrs Client"

  # Даркнесс вносит у чорний список певні версії Forge, які містять вбудовані чіти на дальність удару (Reach) (Forge 1.18.2 — 1.19.3).
  # Встановлення цього параметра в false дозволить таким клієнтам підключатися до сервера.
  # Виключайте на свій страх і ризик.
  disconnect_blacklisted_forge_versions: true

# Packet Settings
packet_settings:

  # Максимальна кількість пропущених транзакцій, після якої гравця викидає з сервера
  # Спрацьовує при FreeCam, BackTrack, Blink
  transaction_skip: 400
  # Скільки часу гравці мають, перш ніж їх викине через тайм-аут? За замовчуванням = 45 секунд
  transaction_time: 45
  # Максимально допустиме від’ємне зміщення таймера гравця, після якого кикаємо (в мілісекундах)
  # Спрацьовує при Timer (0.1), Freeze
  negative_timer: 5000
  # Ця настройка застосовується лише до клієнтів 1.17–1.20.5 на серверах 1.8
  cancel_duplicate_packet: true
  # Ігнорувати ротацію у дублікатних пакетах?
  ignore_duplicate_packet_rotation: true
  # Увімкніть це, щоб заборонити Даркнесс скасовувати пакети pong, отримані від гравців
  # Може покращити сумісність з іншими античитами. Може викликати проблеми з лімітуванням пакетів
  # Не вмикайте, якщо не впевнені у тому, що робите
  disable_pong_cancelling: false
  # Даркнесс іноді скасовує незаконні пакети, наприклад, з таймером, після X скасованих пакетів за секунду
  # Чи слід просто кикати гравця замість цього? Це потрібно, бо деякі лімітери пакетів не враховують пакети, скасовані Даркнесс
  packet_spam_threshold: 100
  # Даркнесс може гарантувати, що гравець, виведений з режиму польоту, не може мати пінг більше X мілісекунд.
  # Це пов'язано з тим, що Даркнесс наразі не перевіряє літаючих гравців.
  max_ping_out_of_flying: 300
  # Максимальний пінг, коли посилення феєрверка знімається з гравця.
  # Це не дозволяє гравцям із високою затримкою використовувати одне посилення феєрверка з надкриллями назавжди.
  max_ping_firework_boost: 1000

# Налаштування команд покарання // Не рекомендується до використання — скоро буде видалено
point_command:

  # Команди, які будуть виконуватися за різних умов (наприклад, при порушеннях)
  '1': darkness rotate %PLAYER%
  '2': darkness shuffle %PLAYER% many
  '3': darkness rotate %PLAYER%
  '4': darkness shuffle %PLAYER% many
  '6': darkness kick %PLAYER% &cПідозра у використанні читів
  '7': darkness crash %PLAYER% particle
  '8': darkness kick %PLAYER% &cПідозра у використанні читів
  '9': darkness ban %PLAYER% &cПідозра у використанні читів
  '21': darkness kick %PLAYER% &cПідозра у використанні читів
  '26': darkness kick %PLAYER% &cПідозра у використанні читів
  '30': darkness ban %PLAYER% &cПідозра у використанні читів
  '34': darkness kick %PLAYER% &cПідозра у використанні читів
  '38': darkness ban %PLAYER% &cПідозра у використанні читів

# Punish Command Settings
punish_command:

  # Яку анімацію покарання повинна показувати Даркнесс перед киком гравця?
  # Анімації: NONE, THOR, FIRE, ERROR, SHAME або RANDOM для вибору випадкової анімації кожен раз
  animation: NONE

  # Чи повинні ми надсилати повідомлення в чат, коли гравець карається Даркнесс?
  broadcast: true

  # Яку команду повинна виконати Даркнесс після завершення анімації покарання? (%nl% для нового рядка)
  # Плейсхолдери: %prefix% -> (Префікс Даркнесс), %player% -> (Гравець, який був покараний), %reason% -> (Причина, вказана в команді покарання Даркнесс)
  command: darkness kick %player% %prefix% %reason%

# Punish Wave Settings
punishwave:

  # Чи ввімкнути Хвилю Покарань?
  # Якщо Хвиля Покарань увімкнена, Даркнесс покарає всіх читерів одночасно
  # Якщо гравець був покараний за допомогою команди /darkness punish при ввімкненій Хвилі Покарань,
  # він буде доданий до черги та покараний, коли почнеться Хвиля Покарань
  enabled: false

  # Чи повинна Даркнесс повідомляти про цю подію?
  broadcast: true

  # Як часто повинна виконуватися Хвиля Покарань? (у хвилинах)
  time: 15

  # Зворотний відлік перед виконанням Хвилі Покарань (-1 щоб вимкнути)
  countdown: 5

# Ban Command Settings
ban_command:

  # Чи повинні ми надсилати повідомлення в чат, коли гравець карається Даркнесс?
  broadcast: true

  # Плейсхолдери: %player% -> (Гравець, який був покараний), %reason% -> (Причина, вказана в команді покарання Даркнесс)
  command: ban %player% %reason%

# Discord Sync Settings
discord:

  # Ви хочете синхронізувати Darkness із вашим Discord-сервером?
  enabled: false

  # Вставте URL вебхука каналу
  webhook_url: ""
  # Заголовок повідомлення
  embed_title: "**:fire: ВИЯВЛЕНО НОВОГО ЧИТЕРА!**"
  # Колір смуги зліва від повідомлення
  embed_color: "#ff0000"

  # Зміст повідомлення
  violation_content:
    - "%player%"
    - ""
    - ":shield: **Режим:**"
    - "%server_name%"
    - ""
    - ":package: **Тип чіту:**"
    - "%check%"
    - ""
    - ":bar_chart: **Рівень:**"
    - "%violations%"
    - ""
    - ":desktop: **Клієнт:**"
    - "%brand%"
    - ""
    - ":pushpin: **Версія:**"
    - "%version%"
    - ""
    - ":signal_strength: **PING | TPS:**"
    - "%ping% | %tps%"

  # Бажаєте, щоб Darkness надсилала повідомлення в Discord,
  # коли гравці караються під час Punish Wave?
  punishwave: false
  punishwave_title: "**:fire: ВИЯВЛЕНО ХВИЛЮ НОВИХ ЧИТЕРІВ!**"

  # Зміст повідомлення
  punishwave_content:
    - ":shield: **Режим**"
    - "%server_name%"
    - ""
    - ":busts_in_silhouette: **Покарані гравці**"
    - "%players_punishwave%"
    - ""

  # Заголовок додаткового поля в ембед
  embed_field: "Інформація:"

# Log Settings
logs:

  # Який тип логування використовувати Darkness?
  # Типи: YAML_ONE, YAML_DAYS, MYSQL, SQLITE, NONE
  # 1. YAML_ONE - Логує всі флаги в один файл data.yml
  # 2. YAML_DAYS - Логує кожен день в окремий файл у папці logs
  # 3. SQLITE - Логує в базу даних SQLite
  # 4. MYSQL - Логує в базу даних MySQL
  # 5. NONE - Виключає логування
  type: YAML_ONE

  # Логи, старші за це значення в днях, будуть видалені
  clear_days: 7

  # Налаштування MySQL (потребує тип MYSQL)
  mysql:
    host: localhost
    port: 3306
    database: database
    user: root
    password: ''
    use_ssl: false

    # Налаштування пулу з'єднань MySQL
    # Не змінюйте, якщо не знаєте, що робите
    pool_settings:
      maximum_pool_size: 50
      minimum_idle: 30
      maximum_lifetime: 1800000
      connection_timeout: 30000
      leak_detection_threshold: 0

## InformationHider Check
InformationHider:

  # Увімкнути модуль приховування інформації?
  enabled: true

  # Перевіряти тільки гравців чи всіх істот?
  onlyForPlayers: true

  # Приховує дані про гравців та мобів, щоб чити не могли отримати зайву інформацію.
  # Для звичайних гравців нічого не зміниться, але чити не працюватимуть як треба.
  parts:
    # Спуфить здоров’я — гравці та моби завжди показують фейкове здоров'я
    # Корисно проти хп-барів у модах та читах
    health:
      # Вкажіть значення, яке Darkness повинна спуфити для гравців від 0 до 20.
      # Значення 0 зламає багато KillAura хаків, але також порушує анімацію ходьби.
      # Не рекомендовано, якщо не хочете, щоб гравці ходили як "місячною походкою".
      value: 20
      # Якщо увімкнено, буде використовуватися випадкове значення від 0 до 20.
      # Менш помітно для гравців і краще зберігає процес гри.
      random: false

    # Маскує внутрішні дані гравця, щоб модулі читів не могли їх використовувати.
    # Приховує реальний рівень досвіду, щоб запобігти його відображенню в читах.
    xp: true
    # Приховує рівень кисню, щоб чити не показували точну кількість повітря.
    air: true
    # Приховує рівень ситості. Ламає роботу функцій AutoEat у чит-клієнтах.
    saturation: true
    # Приховує реальний пінг у табі. Запобігає деяким обходам у модулях AntiBot.
    ping: true
    # Приховує режим гри. Чити завжди бачитимуть гравця в Creative.
    gamemode: true
    # Надсилає фейковий сид світу, щоб чити не могли знайти руду та структури за сидом.
    seed: true
    # Приховує дані про здоров'я та статистику зі скорбордів та таба.
    scoreboard: true

    # Маскує екіпірування та візуальні ефекти персонажів.
    # Приховує зачарування на броні та предметах, щоб чити не бачили їхній тип та рівень.
    enchant: true
    # Приховує точну кількість предметів у руках та інвентарі.
    item_count: true
    # Замінює справжні назви предметів у руках на випадкові.
    item_name: true
    # Приховує назви та кількість предметів, що лежать на землі.
    item_drop: true
    # Завжди показує повну міцність речей, щоб чити не бачили зношення броні.
    durability: true
    # Приховує ефекти зілля від чужих очей (щоб не бачили силу, швидкість тощо).
    potion: true
    # Спамить читу фейковими пакетами ефектів, повністю забиваючи його PotionList сміттям.
    end_effect: true
    # Створює навколо гравця невидимих гравців. Змушує чіти малювати хибні лінії та бокси у порожні місця.
    esp_tracer: true
    # Перемішує предмети в інвентарі під час руху, ламаючи роботу AutoTotem та InvWalk у читах.
    inventory: true

    # Спамить читу помилковими пакетами вибухів тотемів, використання щитів та кидків ендер-перлів.
    # Це дозволяє ламати сповіщення в читах про спрацювання тотема, щита або роботу TargetPearl.
    fake_action:
      # Вкажіть шанс спрацювання фейкових ефектів для читів від 1 до 100.
      # Не рекомендується ставити значення >= 25.0, це створить зайве навантаження і може призвести до лагів.
      # Вкажіть значення -1, щоб повністю вимкнути.
      totem_chance: 6.5
      shield_chance: 6.0
      pearl_chance: 4.0

    # Модуль створює фейкових модераторів у табі, щоб приховати справжніх модераторів від читів.
    # Не хвилюйтесь, ці боти існують лише на чіт-клієнті, реальні гравці їх не бачать.
    fake_staff:
      # Чи потрібно нам створювати фальшивих ботів для маскування реальної модерації
      enabled: true
      # Якщо true, Darkness завжди створює ботів з випадковими іменами.
      # Це допомагає сумісності з деякими серверами, але іноді дозволяє обійти StaffList.
      only_random_name: false
      # Вкажіть реальні префікси вашої модерації, які відображатимуться у фейкових ботів.
      roles:
        - "&cAdmin"
        - "&cStaff"
        - "&cHelper"
        - "&cModer"
      # Рекомендується встановити кількість ботів >= 60, щоб чіти не змогли відфільтрувати справжніх модераторів.
      bots: 60

    # Налаштування глядачів (потрібен дозвіл: darkness.spectator)
    spectators:
      # Приховувати глядачів тільки у цих світах. Залиште пустим, щоб дозволити всі світи.
      allowed_worlds:
        - ""
      # Приховати всіх глядачів з permission darkness.spectator, незалежно від активності.
      hide_spectators: true

# Compatibility Settings
compatibility:

  # Увімкніть, якщо у вас кросплатформений проєкт. Це виключить гравців Bedrock
  # із перевірок, допоможе уникнути хибних спрацювань.
  geyser: true

  # Увімкніть, якщо ви дозволяєте мод ItemsScroller. Це дозволить уникнути
  # хибних спрацювань при швидкому переміщенні предметів.
  itemsScroller: false

  # Увімкніть, якщо ви дозволяєте мод TapeMouse. Це запобіжить прапорцям
  # на афк фармилках, де удари йдуть в один і той самий таймінг.
  tapeMouse: false

  # Увімкніть, якщо ви дозволяєте макроси на клавіші. Це допоможе уникнути
  # хибних спрацювань при введенні команд під час ходьби.
  keybind: false

  # Чи потрібно враховувати кінематографічну камеру?
  # Наполегливо рекомендується не вмикати цю опцію, оскільки це зробить перевірки аіму менш ефективними.
  # У реальному бою жоден гравець не буде битися, використовуючи кінематографічну камеру.
  account_cinematic: false

# Увімкнути запис у журнал плагінів, які впроваджені в netty при підключенні для налагодження проблем сумісності
debug_pipeline_on_join: false

# Увімкнути експериментальні перевірки
experimental_checks: false

# Логер для перегляду пакетів, які надсилають гравці, корисно для розробників.
packet_logger:
  enabled: false

  # Вкажіть нижче гравців, чиї пакети будуть логуватися в консолі.
  whitelist:
    - 1hendex

  # Список пакетів, які потрібно ігнорувати.
  # Щоб дізнатися правильні імена, відкрийте GitHub PacketEvents і знайдіть назви.
  # Шлях: https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/protocol/packettype/PacketType.java
  ignore:
    - WINDOW_CONFIRMATION
    - KEEP_ALIVE
    - PONG

# Назва сервера, яка буде відображатися в логах гравців та повідомленнях Discord
server_name: Darkness Server

# Вкажіть назву або назви для команд Даркнесс.
# Перша назва в списку стане основною командою плагіна.
# Зміни застосовуються лише після перезавантаження сервера.
command_name: darkness,dl

# Чи слід нам вимкнути дозвіл на обхід?
# Якщо ввімкнено, Даркнесс перевірятиме всіх гравців, включаючи операторів
# Вимкніть це для покращення продуктивності
disable_bypass_permission: false

config:
  checks_updates: true
  lang: uk
  version: 1
